config/routes.rb
Rails.application.routes.draw do

  get 'book/index'
  post 'book/addbooks'

  get 'book/gotoSelect'
  post 'book/selectsolr'



  get 'usercenter/index'

  post 'login/loginuser'
  get 'login/index'
  get 'welcome/index'
  



  resources :usertables
  resources :welcome
  root 'welcome#index'
end

app/models/book.rb
class Book
  include Mongoid::Document
  field :bookname, type: String
  field :bookkey, type: String
  field :bookmiaosu, type: String
  validates :bookname, presence: true,uniqueness: true
  has_many :booksuser
end

app/models/booksuser.rb
class Booksuser
  include Mongoid::Document
  belongs_to :book
  belongs_to :usertable
end

app/models/usertable.rb
class Usertable
  include Mongoid::Document
  field :name, type: String
  field :pwd, type: String
  validates :name, presence: true, uniqueness: true, length: {maximum: 20, too_long: "最大长度为%{count}个字符"}
  has_many :booksuser
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_controller.rb
require '~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems.rb'
require '~/.rvm/gems/ruby-2.3.1/gems/rsolr-1.1.1/lib/rsolr.rb'
class BookController < ApplicationController
  def index
    @booklists=Book.all
  end

  def addbooks
    @book = Book.new(books_params)
    respond_to do |format|
      if @book.save
        # Direct connection
        solr = RSolr.connect :url => 'http://localhost:8080/solr/books_core'
        documents = [{:id=>@book.__id__, :bookname=>@book.bookname, :bookkey=>@book.bookkey, :bookmiaosu=>@book.bookmiaosu}]
        solr.add documents
        format.html { redirect_to book_index_path, notice: '图书保存成功.' }
      else
        format.html { redirect_to book_index_path, notice: '图书保存失败.' }
      end
    end
  end


  def gotoSelect
    @book=Book.new
  end

  def selectsolr
    @book = Book.new(books_name)
    @keyworld=@book.bookname
    solr = RSolr.connect :url => 'http://localhost:8080/solr/books_core'
    response = solr.get 'select', :params => {:q=>"bookname:#{@book.bookname} bookkey:#{@book.bookname} bookmiaosu:#{@book.bookname}", :start=>0,  :rows=>10}
    @books = response["response"]["docs"]
    puts response["response"]["docs"]
  end

  def books_params
    params.require(:book).permit(:bookname, :bookkey,:bookmiaosu)
  end
  def books_name
    params.require(:book).permit(:bookname)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  #这是是一个页面跳转跳转到用户的登录页面
  def index
  end

  #用户登录使用
  def loginuser


    @usertable = Usertable.new(usertable_params)
    @selectusertable = Usertable.where(:name => @usertable.name)

    #在数据库中查询是否存在这个用户名
    if @selectusertable.size ==0
      respond_to do |format|
        format.html { redirect_to login_index_url, notice: '没有在数据库中找到您的用户名.' }
      end
      return
    end
    #判断用户输入的密码是不是和我们的密码相同
    unless @selectusertable[0].pwd.to_s==@usertable.pwd.to_s
      respond_to do |format|
        format.html { redirect_to login_index_url, notice: '对不起您输入的密码是错误的.' }
      end
      return
    end

    #保存session并且返回到用户中心页面
    session[:usersession] = @selectusertable[0].book
    respond_to do |format|

      format.html { redirect_to usercenter_index_url }
    end
  end

  def usertable_params
    params.require(:usertable).permit(:name, :pwd)
  end
end

app/controllers/usercenter_controller.rb
class UsercenterController < ApplicationController
  #对访问进来的链接进行session判断
  before_action :session_c, only: [:index]

  def index
  end

  def session_c
    if session[:usersession]==nil then
      respond_to do |format|
        format.html {redirect_to login_index_url }
      end
    end
  end
end

app/controllers/usertables_controller.rb
class UsertablesController < ApplicationController
  #再进行下面操作时通过id查询到相应的对象
  before_action :set_usertable, only: [:show, :edit, :update, :destroy]

  #查询所有的记录 # GET /usertables   # GET /usertables.json
  def index
    @usertables = Usertable.all
  end

  #删除用户信息 # DELETE /usertables/1  # DELETE /usertables/1.json
  def destroy
    @usertable.destroy
    respond_to do |format|
      format.html { redirect_to usertables_url, notice: '用户已经成功删除.' }
      format.json { head :no_content }
    end
  end
  #跳转到添加用户页面 # GET /usertables/new
  def new
    @usertable = Usertable.new
  end

  #创建一个用户 # POST /usertables  # POST /usertables.json
  def create
    @usertable = Usertable.new(usertable_params)
    respond_to do |format|
      if @usertable.save
        format.html { redirect_to @usertable, notice: '用户保存成功.' }
        format.json { render :show, status: :created, location: @usertable }
      else
        format.html { render :new }
        format.json { render json: @usertable.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /usertables/1
  # GET /usertables/1.json
  def show
  end
  # GET /usertables/1/edit
  def edit
  end
  # PATCH/PUT /usertables/1
  # PATCH/PUT /usertables/1.json
  def update
    respond_to do |format|
      if @usertable.update(usertable_params)
        format.html { redirect_to @usertable, notice: '用户信息更新成功.' }
        format.json { render :show, status: :ok, location: @usertable }
      else
        format.html { render :edit }
        format.json { render json: @usertable.errors, status: :unprocessable_entity }
      end
    end
  end



  private
  def set_usertable
    @usertable = Usertable.find(params[:id])
  end


    # Never trust parameters from the scary internet, only allow the white list through.
    def usertable_params
      params.require(:usertable).permit(:name, :pwd)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/usercenter_helper.rb
module UsercenterHelper
end

app/helpers/usertables_helper.rb
module UsertablesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/book/gotoSelect.html.erb
<%= form_for :book , url: book_selectsolr_path do |f| %>
    <div class="field">
      <%= f.label :书名 %><br>
      <%= f.text_field :bookname %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/book/index.html.erb
<h1>添加图书</h1>
<table>
  <thead>
  <tr>
    <th>书名</th>

  </tr>
  </thead>
  <!--循环从数据库中读取到的数据-->
  <tbody>
  <% @booklists.each do |book| %>
      <tr>
        <td><%= book.bookname %></td>

      </tr>
  <% end %>
  </tbody>
</table>



<%= form_for :book , url: book_addbooks_path do |f| %>
    <div class="field">
      <%= f.label :书名 %><br>
      <%= f.text_field :bookname %>
    </div>
    <div class="field">
      <%= f.label :关键字 %><br>
      <%= f.text_field :bookkey %>
    </div>
    <div class="field">
      <%= f.label :描述 %><br>
      <%= f.text_field :bookmiaosu %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%=notice%>

app/views/book/selectsolr.html.erb
<h1>关键字:<%=@keyworld%></h1>
<table>
  <thead>
  <tr>
    <th>书名</th>
  </tr>
  </thead>
  <!--循环从数据库中读取到的数据-->
  <tbody>
  <% @books.each do |doc|%>
      <tr>
        <td><%= doc["bookname"] %></td>
        <td><%= link_to '关联书名', usertable_path(doc["id"]) %> </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<%=notice%>
<%= form_for :usertable , url: login_loginuser_path do |f| %>
    <div class="field">
      <%= f.label :用户名 %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :密码 %><br>
      <%= f.text_field :pwd %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/login/loginuser.html.erb
<h1>Login#loginuser</h1>
<p>Find me in app/views/login/loginuser.html.erb</p>

app/views/usercenter/index.html.erb
<h1>Usercenter#index</h1>
<p>Find me in app/views/usercenter/index.html.erb</p>
dsakodakadj

app/views/usertables/_form.html.erb
<%= form_for(@usertable) do |f| %>
  <% if @usertable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usertable.errors.count, "error") %> prohibited this usertable from being saved:</h2>

      <ul>
      <% @usertable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :用户名 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :密码 %><br>
    <%= f.text_field :pwd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usertables/edit.html.erb
<h1>Editing Usertable</h1>

<%= render 'form' %>

<%= link_to '查看信息', usertable_path(@usertable) %> |
<%= link_to '返回信息', usertables_path %>

app/views/usertables/index.html.erb
<!--用于显示返回回来的信息-->
<p id="notice"><%= notice %></p>
<h1>这里是所有的用户信息</h1>
<table>
  <thead>
    <tr>
      <th>用户名</th>
      <th>密码</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>
  <!--循环从数据库中读取到的数据-->
  <tbody>
    <% @usertables.each do |usertables| %>
      <tr>
        <td><%= usertables.name %></td>
        <td><%= usertables.pwd %></td>
        <td><%= link_to "显示详细信息", usertable_path(usertables) %></td>
        <td><%= link_to "修改数据", edit_usertable_path(usertables) %></td>
        <td><%= link_to "删除数据", usertable_path(usertables), method: :delete, data: { confirm: '您确定要修改吗?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "注册用户", new_usertable_path %>
<br>

app/views/usertables/new.html.erb
<h1>New Usertable</h1>

<%= render 'form' %>

<%= link_to 'Back', usertables_path %>

app/views/usertables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>用户名:</strong>
  <%= @usertable.name %>
</p>

<p>
  <strong>密码:</strong>
  <%= @usertable.pwd %>
</p>

<%= link_to '修改信息', edit_usertable_path(@usertable) %> |
<%= link_to '返回信息', usertables_path %>

app/views/welcome/index.html.erb
<h1>网站首页</h1>
<p><%= link_to '查询用户', usertables_path %></p>
<p><%= link_to '用户注册', new_usertable_path %></p>
<p><%= link_to '用户登录', login_index_path %></p>
<p><%= link_to '添加图书', book_index_path %></p>
<p><%= link_to '图书查询', book_gotoSelect_path %></p>